### ISSUE TITLE
"validateOnly" flag

### ISSUE THREAD

**Issue by KarlBaumann** [Hanisch-IT/kraken-api#12]
Is there a proper way how to enable "validateOnly" flag, when making new order?
When I try to set it, I get "Undefined index: txid"

**Comment by Hanisch-IT** [comment]
Hi,

Sorry for the late response. Was in holiday berween the years.


Will check this and gibe you a feedback

**Comment by Hanisch-IT** [comment]
Hi @KarlBaumann,

i added a release where you can create valideOnly-Orders withoutneed to change anything.

Checkout the example `03_AddOrder.php`

Regards

**Comment by KarlBaumann** [comment]
Thanks!
Works great!
